services:
  db:
    image: postgres:15
    container_name: products-db
    restart: always
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc@123
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d products_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - backend_net

  backend:
    build:
      context: ./products-backend
      dockerfile: Dockerfile
    container_name: products-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/products_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: abc@123
    networks:
      - frontend_net
      - backend_net

  frontend:
    build:
      context: ./products-ui
      dockerfile: Dockerfile
    container_name: products-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - frontend_net

networks:
  frontend_net:
  backend_net:
